export default {
    "vulkan-notes": {
        title: "Vulkan学习笔记",
        tags: ["图像处理", "图形学", "计算机", "学习笔记"],
        component: 'vulkan-notes',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "image-display-coordinate": {
        title: "图片渲染中缩放平移的坐标系变换",
        tags: ["图像处理", "图形学", "计算机"],
        component: 'image-display-coordinate',
        createdAt: "2022-9-7",
        updatedAt: "2022-9-7",
        author: "Yi Jin",
    },
    "photoshop-curve-implement": {
        title: "Photoshop曲线工具的实现",
        tags: ["Photoshop", "图像处理", "数学", "线性代数", "计算机"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "layer-color-blending-algorithm": {
        title: "图层颜色混合算法",
        tags: ["图像处理", "色彩学"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "kubelka-munk-color-blending": {
        title: "Kubelka-Munk 方程与印刷配色",
        tags: ["图像处理", "色彩学"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "svd-and-image-compression": {
        title: "SVD与一种图像压缩算法",
        tags: ["图像处理", "算法", "压缩"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "pattern-based-halftoning-algorithm": {
        title: "一种基于图案的Halftoning算法",
        tags: ["图像处理", "算法"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "lzw-compression-algorithm": {
        title: "LZW压缩算法详解与分析",
        tags: ["算法", "压缩", "计算机"],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "image-semi-automatic-stitching-algorithm": {
        title: "一种半自动的图像拼接算法",
        tags: ["图像处理", "算法",],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "image-semi-automatic-orthorectification-algorithm": {
        title: "一种半自动的图像畸形正交校正算法",
        tags: ["图像处理", "算法",],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "image-minimum-pattern-matching-algorithm": {
        title: "一种在重复图案构成的图像中匹配最小图案的算法",
        tags: ["图像处理", "算法",],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
    "flat-screen-automatic-split-algorithm": {
        title: "一种针对平网图案印刷的开路算法",
        tags: ["图像处理", "算法",],
        component: 'blank',
        createdAt: "2022-8-12",
        updatedAt: "2022-8-29",
        author: "Yi Jin",
    },
};